# Generated by Django 4.2.7 on 2023-12-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTripDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('startLoc', models.FloatField()),
                ('endLoc', models.FloatField()),
                ('owner', models.TextField()),
                ('driver', models.TextField()),
                ('datasets', models.TextField()),
                ('trp1', models.TextField(null=True)),
                ('trp2', models.TextField(null=True)),
                ('trp3', models.TextField(null=True)),
                ('trp4', models.FloatField(null=True)),
                ('trp5', models.FloatField(null=True)),
                ('trp6', models.TextField(null=True)),
                ('trp7', models.TextField(null=True)),
                ('trp8', models.TextField(null=True)),
                ('trp9', models.FloatField(null=True)),
                ('trp10', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='DLUrl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='KYCurls',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='phNo',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.truck'),
        ),
    ]
