# Generated by Django 4.2.7 on 2023-12-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newtripdetails_alter_driverdetail_dlurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='owenerid',
        ),
        migrations.AddField(
            model_name='data',
            name='tripdetail',
            field=models.ManyToManyField(to='api.newtripdetails'),
        ),
        migrations.AddField(
            model_name='truck',
            name='oweners',
            field=models.ManyToManyField(to='api.ownerdetail'),
        ),
        migrations.RemoveField(
            model_name='driverdetail',
            name='truck',
        ),
        migrations.AlterField(
            model_name='newtripdetails',
            name='datasets',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='newtripdetails',
            name='driver',
        ),
        migrations.AlterField(
            model_name='newtripdetails',
            name='endLoc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='newtripdetails',
            name='owner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newtripdetails',
            name='startLoc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ownerdetail',
            name='drivers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ownerdetail',
            name='trips',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ownerdetail',
            name='trucks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='datasets',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='driver',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='endLoc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='owner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='startLoc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='Make',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='Model',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='Plate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='RCUrl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='chassisNo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='lastKLoc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='driverdetail',
            name='truck',
            field=models.ManyToManyField(null=True, to='api.truck'),
        ),
        migrations.AddField(
            model_name='newtripdetails',
            name='driver',
            field=models.ManyToManyField(null=True, to='api.driverdetail'),
        ),
    ]
