# Generated by Django 4.2.7 on 2023-12-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_truck_owenerid_data_tripdetail_truck_oweners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='oweners',
        ),
        migrations.AlterField(
            model_name='ownerdetail',
            name='trucks',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='api.truck'),
            preserve_default=False,
        ),
    ]
