# Generated by Django 4.2.7 on 2023-12-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_truck_oweners_alter_ownerdetail_trucks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerdetail',
            name='trucks',
        ),
        migrations.AddField(
            model_name='truck',
            name='ownerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ownerdetail'),
            preserve_default=False,
        ),
    ]
