# Generated by Django 4.2.7 on 2023-12-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_ownerdetail_trucks_truck_ownerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtripdetails',
            name='driver',
        ),
        migrations.AddField(
            model_name='newtripdetails',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.driverdetail'),
            preserve_default=False,
        ),
    ]
