# Generated by Django 4.2.7 on 2023-12-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_newtripdetails_driver_newtripdetails_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='ownerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ownerdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newtripdetails',
            name='ownerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ownerdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newtripdetails',
            name='truckid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.truck'),
            preserve_default=False,
        ),
    ]
