# Generated by Django 5.0.7 on 2024-07-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_driverdetail_ownerid_newtripdetails_ownerid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripdetail",
            name="Average_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="C1",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="C2",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="C3",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="C4",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="C5",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="Distance_Travelled",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="Risk_Instance",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="Score",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="Trip_No",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="Trip_time",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tripdetail",
            name="Tripdetail_id",
            field=models.TextField(null=True),
        ),
    ]
