# Generated by Django 5.0.7 on 2024-07-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_tripdetail_average_speed_tripdetail_c1_tripdetail_c2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripdetail",
            name="createdAt",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="datasets",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="details",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="endLoc",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="endTime",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="startLoc",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="startTime",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp1",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp10",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp2",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp3",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp4",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp5",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp6",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp7",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp8",
        ),
        migrations.RemoveField(
            model_name="tripdetail",
            name="trp9",
        ),
        migrations.AlterField(
            model_name="tripdetail",
            name="Tripdetail_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
