from django.db import models

# Create your models here.


class UserDetail(models.Model):
    mob = models.BigIntegerField(null=False)
    Trip = models.BigIntegerField(null=True)


class CarDetail(models.Model):
    mob_id = models.ForeignKey(UserDetail, on_delete=models.CASCADE)
    
    Trip_no = models.IntegerField(null=True)
    Trip_time = models.CharField(null=True, max_length=50)
    ax = models.FloatField(null=True)
    ay = models.FloatField(null=True)
    az = models.FloatField(null=True)
    gx = models.FloatField(null=True)
    gy = models.FloatField(null=True)
    gz = models.FloatField(null=True)
    mx = models.FloatField(null=True)
    my = models.FloatField(null=True)
    mz = models.FloatField(null=True)
    speed = models.FloatField(null=True)
    GPS = models.TextField(null=True)
    C1 = models.FloatField(null=True)
    C2 = models.FloatField(null=True)
    C3 = models.FloatField(null=True)
    C4 = models.FloatField(null=True)
    C5 = models.FloatField(null=True)
    C6 = models.FloatField(null=True)
    C7 = models.FloatField(null=True)
    C8 = models.FloatField(null=True)
    C9 = models.FloatField(null=True)
    C10 = models.FloatField(null=True)
    C11 = models.FloatField(null=True)
    C12 = models.FloatField(null=True)
    C13 = models.TextField(null=True)
    C14 = models.TextField(null=True)
    C15 = models.TextField(null=True)
    resultant = models.FloatField(null=True)
    # Hard_Acc = models.IntegerField(null=True)
    # Hard_brake = models.IntegerField(null=True)
    # Hard_cornering = models.IntegerField(null=True)



class OwnerDetail(models.Model):
    id = models.AutoField(primary_key=True)
    CompanyDesc = models.TextField()
    CompanyName = models.TextField()
    CompanyEmail = models.TextField()
    CompanyAddress = models.TextField()
    phNo = models.CharField(max_length=12)
    drivers = models.TextField(null=True)
    trips = models.TextField(null=True)
    O1 = models.TextField(null=True)
    O2 = models.TextField(null=True)
    O3 = models.TextField(null=True)
    O4 = models.FloatField(null=True)
    O5 = models.FloatField(null=True)
    O6 = models.TextField(null=True)
    O7 = models.TextField(null=True)
    O8 = models.TextField(null=True)
    O9 = models.FloatField(null=True)
    O10 = models.FloatField(null=True)


class truck(models.Model):
    id = models.AutoField(primary_key=True)
    lastKLoc = models.FloatField(null=True)
    RCUrl = models.TextField(null=True)
    Plate = models.TextField(null=True)
    Make = models.TextField(null=True)
    Model = models.TextField(null=True)
    chassisNo = models.TextField(null=True)
    ownerid = models.ForeignKey(OwnerDetail, on_delete=models.CASCADE)
    T1 = models.TextField(null=True)
    T2 = models.TextField(null=True)
    T3 = models.TextField(null=True)
    T4 = models.FloatField(null=True)
    T5 = models.FloatField(null=True)
    T6 = models.TextField(null=True)
    T7 = models.TextField(null=True)
    T8 = models.TextField(null=True)
    T9 = models.FloatField(null=True)
    T10 = models.FloatField(null=True)


class DriverDetail(models.Model):
    id = models.AutoField(primary_key=True)
    CompanyName = models.TextField(null = True)
    phNo = models.CharField(max_length=12, null= True)
    PhotoUrl = models.TextField(null = True)
    truck = models.ManyToManyField(truck, null=True)
    DLUrl = models.TextField(null=True)
    KYCurls = models.TextField(null= True)
    ownerid = models.ForeignKey(OwnerDetail, on_delete=models.CASCADE)
    D1 = models.TextField(null=True)
    D2 = models.TextField(null=True)
    D3 = models.TextField(null=True)
    D4 = models.FloatField(null=True)
    D5 = models.FloatField(null=True)
    D6 = models.TextField(null=True)
    D7 = models.TextField(null=True)
    D8 = models.TextField(null=True)
    D9 = models.FloatField(null=True)
    D10 = models.FloatField(null=True)
    


class TripDetail(models.Model):
    id = models.AutoField(primary_key=True)
    Tripdetail_id = models.BigIntegerField(null=True)
    Trip_No = models.BigIntegerField(null=True)
    Risk_Instance = models.FloatField(null=True)
    Average_speed = models.FloatField(null=True)
    Trip_time = models.FloatField(null=True)
    Distance_Travelled = models.FloatField(null=True)
    Score = models.FloatField(null=True)
    C1 = models.TextField(null=True)
    C2 = models.TextField(null=True)
    C3 = models.TextField(null=True)
    C4 = models.FloatField(null=True)
    C5 = models.FloatField(null=True)

    
class NewTripDetails(models.Model):
    id = models.AutoField(primary_key=True)
    startTime = models.DateTimeField(auto_now_add=True)
    endTime = models.DateTimeField(auto_now_add=True)
    details = models.TextField(null=True)
    createdAt = models.DateTimeField(auto_now_add=True)
    startLoc = models.FloatField(null=True)
    endLoc = models.FloatField(null=True)
    owner = models.TextField(null=True)
    driver = models.ForeignKey(DriverDetail,on_delete=models.CASCADE)
    ownerid = models.ForeignKey(OwnerDetail, on_delete=models.CASCADE)
    truckid = models.ForeignKey(truck, on_delete=models.CASCADE) 
    datasets = models.TextField(null=True)
    trp1 = models.TextField(null=True)
    trp2 = models.TextField(null=True)
    trp3 = models.TextField(null=True)
    trp4 = models.FloatField(null=True)
    trp5 = models.FloatField(null=True)
    trp6 = models.TextField(null=True)
    trp7 = models.TextField(null=True)
    trp8 = models.TextField(null=True)
    trp9 = models.FloatField(null=True)
    trp10 = models.FloatField(null=True)



class Data(models.Model):
    id = models.AutoField(primary_key=True)
    docURL = models.TextField()
    distance = models.IntegerField()
    startTime = models.DateTimeField(auto_now=True)
    endTime = models.DateTimeField(auto_now = True)
    addEvents = models.IntegerField()
    arcScore = models.FloatField()
    breakEvents = models.IntegerField()
    breakScore = models.FloatField()
    overSpeedEvents = models.IntegerField()
    overSpeedScore = models.FloatField()
    riskScore = models.FloatField()
    safetyScore = models.FloatField()
    tripdetail = models.ManyToManyField(NewTripDetails)
    dt1 = models.TextField(null=True)
    dt2 = models.TextField(null=True)
    dt3 = models.TextField(null=True)
    dt4 = models.FloatField(null=True)
    dt5 = models.FloatField(null=True)
    dt6 = models.TextField(null=True)
    dt7 = models.TextField(null=True)
    dt8 = models.TextField(null=True)
    dt9 = models.FloatField(null=True)
    dt10 = models.FloatField(null=True)
